runtime: nodejs18
automatic_scaling:
  min_instances: 1
  max_instances: 4
  cpu_utilization:
    target_utilization: 0.5
service: angular
handlers:
  - url: /(.+\.js)
    static_files: dist/crictrix2/\1
    upload: dist/crictrix2/(.+\.js)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.css)
    static_files: dist/crictrix2/\1
    upload: dist/crictrix2/(.+\.css)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.png)
    static_files: dist/crictrix2/\1
    upload: dist/crictrix2/(.+\.png)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.jpg)
    static_files: dist/crictrix2/\1
    upload: dist/crictrix2/(.+\.jpg)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.gif)
    static_files: dist/crictrix2/\1
    upload: dist/crictrix2/(.+\.gif)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.svg)
    static_files: dist/crictrix2/\1
    upload: dist/crictrix2/(.+\.svg)
    secure: always
    redirect_http_response_code: 301

  - url: /favicon.ico
    static_files: dist/crictrix2/favicon.ico
    upload: dist/crictrix2/favicon.ico
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.json)
    static_files: dist/crictrix2/\1
    upload: dist/crictrix2/(.+\.json)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+)
    static_files: dist/crictrix2/index.html
    upload: dist/crictrix2/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /
    static_files: dist/crictrix2/index.html
    upload: dist/crictrix2/index.html
    secure: always
    redirect_http_response_code: 301


